coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 10%

flag_management:
  individual_flags:
    - name: "@justkits/icons"
      paths:
        - "packages/icons/"

    - name: "@justkits/svgs-core"
      paths:
        - "packages/_svgs-core/"

    - name: "@justkits/eslint"
      paths:
        - "packages/eslint/"

    - name: "@justkits/react-jwt"
      paths:
        - "packages/react-jwt/"

    - name: "@justkits/logos"
      paths:
        - "packages/logos/"

comment:
  layout: "diff, flags, files"
  behavior: "default"
  require_changes: false
