packages:
  - packages/*

catalog:
  '@types/node': 25.0.2
  '@vitest/coverage-v8': 4.0.14
  eslint: 9.38.0
  prettier: ^3.7.3
  typescript: 5.9.3
  vitest: 4.0.14

ignoredBuiltDependencies:
  - esbuild
