packages:
  - apps/*
  - configs/*
  - packages/*

catalog:
  '@testing-library/react': 16.3.2
  '@types/node': 25.5.0
  '@types/react': 19.2.14
  '@vitest/coverage-v8': 4.1.2
  eslint: 9.39.2
  jsdom: 29.0.1
  prettier: 3.8.1
  tsup: 8.5.1
  typescript: 5.9.3
  vitest: 4.1.2

ignoredBuiltDependencies:
  - esbuild
