packages:
  - apps/*
  - configs/*
  - packages/*

catalog:
  '@testing-library/react': 16.3.2
  '@types/node': 25.3.2
  '@types/react': 19.2.14
  '@vitest/coverage-v8': 4.0.18
  eslint: 9.39.2
  jsdom: 28.1.0
  prettier: 3.8.1
  typescript: 5.9.3
  vitest: 4.0.18

ignoredBuiltDependencies:
  - esbuild
