packages:
  - packages/*

catalog:
  '@types/node': 20.19.25
  '@vitest/coverage-v8': 4.0.15
  eslint: 9.39.1
  prettier: ^3.7.4
  typescript: 5.9.3
  vitest: 4.0.15

ignoredBuiltDependencies:
  - esbuild
