packages:
  - packages/*

catalog:
  '@types/node': 25.1.0
  '@vitest/coverage-v8': 4.0.18
  eslint: 9.39.2
  prettier: 3.8.1
  typescript: 5.9.3
  vitest: 4.0.18

ignoredBuiltDependencies:
  - esbuild
