packages:
  - packages/*

catalog:
  "@types/node": ^24.10.1
  "@vitest/coverage-v8": 4.0.14
  eslint: 9.39.1
  prettier: ^3.7.3
  typescript: ^5.9.3
  vitest: ^4.0.14

ignoredBuiltDependencies:
  - esbuild
