packages:
  - packages/*

catalog:
  '@types/node': 20.19.25
  '@vitest/coverage-v8': 4.0.15
  eslint: 9.39.2
  prettier: ^3.7.3
  typescript: 5.9.3
  vitest: 4.0.15

ignoredBuiltDependencies:
  - esbuild
