name: ESLint
description: Run ESLint, and upload results

runs:
  using: "composite"
  steps:
    - name: Lint and Generate SARIF
      id: lint
      continue-on-error: true
      shell: bash
      run: |
        pnpm lint \
          --format @microsoft/eslint-formatter-sarif \
          --output-file eslint-results.sarif

    - name: Upload ESLint SARIF
      if: hashFiles('eslint-results.sarif') != ''
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: eslint-results.sarif
        category: eslint
